# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ec5218d840fa177c4ff3fc64c6f3c091f5c05e5d18368db206f70a949d4698b056bd2dcc887fc14c28cc28ee4b12b7fbf0289083bd8d020dac3b07ad2f04b7d

test:
  secret_key_base: c3e0d27db7775123fa87dd0d7023dbb5ae828f06a1721c9969bd79bde640bcc01bd7c752327ef591e648ef8e52889734a6595c8e536915589099f7fbccfa292a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
